services:
  api:
    image: leandro/scrap-to-api
    pull_policy: never
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - CHROME_PATH=/usr/bin/chromium-browser
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/api
    container_name: scrap-to-api-nodejs
