services:
  api:
    image: leandro/scrap-to-api
    pull_policy: never
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/src/api
    container_name: scrap-to-api-nodejs
